## Server Configuration
SERVER_NAME: "whatsapp-go"
SERVER_IP: "127.0.0.1"
SERVER_PORT: "3000"
SERVER_STORE_PATH: "./config/stores"
SERVER_UPLOAD_PATH: "./config/uploads"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "debug"

## Router Configuration
ROUTER_BASE_PATH: "/api/v1/whatsapp"

## Cryptography Configuration
CRYPT_PRIVATE_KEY_FILE: "./config/keys/private.key"
CRYPT_PUBLIC_KEY_FILE: "./config/keys/public.key"

## Basic Auth Configuration
AUTH_BASIC_PASSWORD: "e37361d8-525a-4556-b0a1-2ed21fe94705"

## WhatsApp Version Configuration
WHATSAPP_CLIENT_VERSION_MAJOR: 2
WHATSAPP_CLIENT_VERSION_MINOR: 2123
WHATSAPP_CLIENT_VERSION_BUILD: 8